nexo.sources = src1
nexo.channels = ch1
nexo.sinks = sink1

nexo.sources.src1.type = exec
nexo.sources.src1.command = tail -F /tmp/app_tail.log
nexo.sources.src1.channels = ch1

nexo.channels.ch1.type = memory
nexo.channels.ch1.capacity = 1000
nexo.channels.ch1.transactionCapacity = 100

nexo.sinks.sink1.type = hdfs
nexo.sinks.sink1.channel = ch1
nexo.sinks.sink1.hdfs.path = hdfs://localhost:9000/nexo/bronze/logs/
nexo.sinks.sink1.hdfs.fileType = DataStream
nexo.sinks.sink1.hdfs.writeFormat = Text
nexo.sinks.sink1.hdfs.filePrefix = app-log
nexo.sinks.sink1.hdfs.batchSize = 20
nexo.sinks.sink1.hdfs.rollInterval = 10
nexo.sinks.sink1.hdfs.rollSize = 0
nexo.sinks.sink1.hdfs.rollCount = 0
